namespace VidShrink.App;

internal static class LanguageCatalog
{
    internal static readonly IReadOnlyDictionary<string, string> EnglishToTurkish = new Dictionary<string, string>
    {
        ["Target-size compression and flexible media conversion."] = "Hedef boyutlu sıkıştırma ve esnek medya dönüştürme.",
        ["SHRINK"] = "KÜÇÜLT",
        ["CONVERT"] = "DÖNÜŞTÜR",
        ["ABOUT"] = "HAKKINDA",
        ["SOURCE"] = "KAYNAK",
        ["Drop any media file here, or browse."] = "Herhangi bir medya dosyasını buraya bırakın veya gözatın.",
        ["BROWSE"] = "GÖZAT",
        ["DURATION"] = "SÜRE",
        ["SIZE"] = "BOYUT",
        ["RESOLUTION"] = "ÇÖZÜNÜRLÜK",
        ["VIDEO CODEC"] = "VİDEO KODEĞİ",
        ["AUDIO"] = "SES",
        ["BITRATE"] = "BİT HIZI",
        ["TARGET"] = "HEDEF",
        ["HALF"] = "YARISI",
        ["Archive"] = "Arşiv",
        ["Sharing"] = "Paylaşım",
        ["Social media"] = "Sosyal medya",
        ["Compatible - H.264"] = "Uyumlu - H.264",
        ["Max compression - H.265"] = "En yüksek sıkıştırma - H.265",
        ["Fast - NVENC"] = "Hızlı - NVENC",
        ["May lower resolution"] = "Çözünürlük düşürülebilir",
        ["May lower frame rate"] = "Kare hızı düşürülebilir",
        ["WHAT IT WILL DO"] = "YAPILACAK İŞLEM",
        ["FFMPEG COMMAND"] = "FFMPEG KOMUTU",
        ["AI SETTINGS"] = "AI AYARLARI",
        ["Optional. Copy a prompt to any chat AI, then paste and validate its JSON answer."] = "İsteğe bağlı. İstemi herhangi bir sohbet AI'ına kopyalayın, ardından JSON yanıtını yapıştırıp doğrulayın.",
        ["COPY PROMPT"] = "İSTEMİ KOPYALA",
        ["APPLY PASTED JSON"] = "JSON'U UYGULA",
        ["BACK TO AUTOMATIC"] = "OTOMATİĞE DÖN",
        ["OUTPUT"] = "ÇIKTI",
        ["STAGE"] = "AŞAMA",
        ["REMAINING"] = "KALAN",
        ["CURRENT OUTPUT SIZE"] = "GÜNCEL ÇIKTI BOYUTU",
        ["SHOW IN FOLDER"] = "KLASÖRDE GÖSTER",
        ["CANCEL"] = "İPTAL",
        ["CONVERSION"] = "DÖNÜŞTÜRME",
        ["Load a source in SHRINK or browse here."] = "KÜÇÜLT sekmesinde kaynak yükleyin veya buradan gözatın.",
        ["BROWSE SOURCE"] = "KAYNAĞA GÖZAT",
        ["CONTAINER"] = "KAPSAYICI",
        ["QUALITY MODE"] = "KALİTE MODU",
        ["Fixed bitrate"] = "Sabit bit hızı",
        ["CRF / BITRATE K"] = "CRF / BİT HIZI K",
        ["Source"] = "Kaynak",
        ["Custom"] = "Özel",
        ["CUSTOM WIDTH x HEIGHT"] = "ÖZEL GENİŞLİK x YÜKSEKLİK",
        ["FRAME RATE"] = "KARE HIZI",
        ["CUSTOM FPS"] = "ÖZEL FPS",
        ["Copy"] = "Kopyala",
        ["Drop"] = "At",
        ["AUDIO BITRATE K"] = "SES BİT HIZI K",
        ["START (HH:MM:SS)"] = "BAŞLANGIÇ (SS:DD:SS)",
        ["END (HH:MM:SS)"] = "BİTİŞ (SS:DD:SS)",
        ["PROGRESS"] = "İLERLEME",
        ["ABOUT VIDSHRINK"] = "VIDSHRINK HAKKINDA",
        ["VidShrink is an offline Windows tool for target-size video compression and format conversion. In SHRINK, the target size becomes a total bitrate budget: audio is reserved first, bits per pixel selects CRF or two-pass encoding, resolution steps down when necessary, and oversize output triggers a measured bitrate correction."] = "VidShrink, hedef boyutlu video sıkıştırma ve format dönüştürme için çevrimdışı bir Windows aracıdır. KÜÇÜLT modunda hedef boyut toplam bit hızı bütçesine dönüşür: önce ses payı ayrılır, piksel başına bit değeri CRF veya iki geçişli kodlamayı seçer, gerektiğinde çözünürlük düşürülür ve büyük çıktı ölçülmüş bit hızı düzeltmesini tetikler.",
        ["AUTOMATIC DECISION TABLE"] = "OTOMATİK KARAR TABLOSU",
        [">= 0.10      Keep resolution, quality-first CRF\n0.05-0.10    Keep resolution, two-pass VBR\n0.03-0.05    Halve high frame rates when needed\n< 0.03       Step down the resolution ladder, then two-pass"] = ">= 0.10      Çözünürlüğü koru, kalite öncelikli CRF\n0.05-0.10    Çözünürlüğü koru, iki geçişli VBR\n0.03-0.05    Gerektiğinde yüksek kare hızını yarıya indir\n< 0.03       Çözünürlük basamağını düşür, sonra iki geçiş",
        ["AI MODE"] = "AI MODU",
        ["AI mode only creates a prompt and validates pasted JSON. No AI is embedded, so VidShrink works offline, asks for no API key, and falls back to the complete automatic engine when an answer is malformed or incompatible."] = "AI modu yalnızca istem oluşturur ve yapıştırılan JSON'u doğrular. Gömülü AI olmadığı için VidShrink çevrimdışı çalışır, API anahtarı istemez ve yanıt bozuk ya da uyumsuz olduğunda eksiksiz otomatik motora döner.",
        ["CODECS"] = "KODEKLER",
        ["H.264 offers the broadest compatibility. H.265 compresses more efficiently. VP9 is a strong WebM choice. AV1 maximizes modern compression at higher CPU cost. Stream copy is fastest and lossless when the destination supports the source streams."] = "H.264 en geniş uyumluluğu sunar. H.265 daha verimli sıkıştırır. VP9, WebM için güçlü bir seçimdir. AV1 daha yüksek işlemci maliyetiyle modern sıkıştırmayı en üst düzeye çıkarır. Hedef kaynak akışlarını desteklediğinde akış kopyalama en hızlı ve kayıpsız seçenektir.",
        ["SYSTEM STATUS"] = "SİSTEM DURUMU",
        ["GITHUB / BY TEKNESYUM"] = "GITHUB / TEKNESYUM",
        ["BUY ME A COFFEE"] = "KAHVE ISMARLA",
        ["idle"] = "boşta"
    };

    internal static readonly IReadOnlyDictionary<string, string> TurkishToEnglish = EnglishToTurkish.ToDictionary(item => item.Value, item => item.Key);
}
