namespace VidShrink.App;

internal static class LanguageCatalog
{
    internal static readonly IReadOnlyDictionary<string, string> EnglishToTurkish = new Dictionary<string, string>
    {
        ["Target-size compression and flexible media conversion."] = "Hedef boyutlu sıkıştırma ve esnek medya dönüştürme.",
        ["SHRINK"] = "KÜÇÜLT",
        ["CONVERT"] = "DÖNÜŞTÜR",
        ["ABOUT"] = "HAKKINDA",
        ["SOURCE"] = "KAYNAK",
        ["Drop any media file here, or browse."] = "Herhangi bir medya dosyasını buraya bırakın veya gözatın.",
        ["BROWSE"] = "GÖZAT",
        ["DURATION"] = "SÜRE",
        ["SIZE"] = "BOYUT",
        ["RESOLUTION"] = "ÇÖZÜNÜRLÜK",
        ["VIDEO CODEC"] = "VİDEO KODEĞİ",
        ["AUDIO"] = "SES",
        ["BITRATE"] = "BİT HIZI",
        ["TARGET"] = "HEDEF",
        ["HALF"] = "YARISI",
        ["Archive"] = "Arşiv",
        ["Sharing"] = "Paylaşım",
        ["Social Media"] = "Sosyal Medya",
        ["Compatible - H.264"] = "Uyumlu - H.264",
        ["Max Compression - H.265"] = "En Yüksek Sıkıştırma - H.265",
        ["Fast - NVENC"] = "Hızlı - NVENC",
        ["May lower resolution"] = "Çözünürlük düşürülebilir",
        ["May lower frame rate"] = "Kare hızı düşürülebilir",
        ["WHAT IT WILL DO"] = "YAPILACAK İŞLEM",
        ["FFMPEG COMMAND"] = "FFMPEG KOMUTU",
        ["AI SETTINGS"] = "AI AYARLARI",
        ["Optional. Copy a prompt to any chat AI, then paste and validate its JSON answer."] = "İsteğe bağlı. İstemi herhangi bir sohbet AI'ına kopyalayın, ardından JSON yanıtını yapıştırıp doğrulayın.",
        ["COPY PROMPT"] = "İSTEMİ KOPYALA",
        ["APPLY PASTED JSON"] = "JSON'U UYGULA",
        ["BACK TO AUTOMATIC"] = "OTOMATİĞE DÖN",
        ["OUTPUT"] = "ÇIKTI",
        ["STAGE"] = "AŞAMA",
        ["REMAINING"] = "KALAN",
        ["CURRENT OUTPUT SIZE"] = "GÜNCEL ÇIKTI BOYUTU",
        ["SHOW IN FOLDER"] = "KLASÖRDE GÖSTER",
        ["CANCEL"] = "İPTAL",
        ["CONVERSION"] = "DÖNÜŞTÜRME",
        ["Load a source in SHRINK or browse here."] = "KÜÇÜLT sekmesinde kaynak yükleyin veya buradan gözatın.",
        ["BROWSE SOURCE"] = "KAYNAĞA GÖZAT",
        ["CONTAINER"] = "KAPSAYICI",
        ["QUALITY MODE"] = "KALİTE MODU",
        ["Fixed Bitrate"] = "Sabit Bit Hızı",
        ["CRF / BITRATE K"] = "CRF / BİT HIZI K",
        ["Source"] = "Kaynak",
        ["Custom"] = "Özel",
        ["CUSTOM WIDTH x HEIGHT"] = "ÖZEL GENİŞLİK x YÜKSEKLİK",
        ["FRAME RATE"] = "KARE HIZI",
        ["CUSTOM FPS"] = "ÖZEL FPS",
        ["Copy"] = "Kopyala",
        ["Drop"] = "At",
        ["AUDIO BITRATE K"] = "SES BİT HIZI K",
        ["START (HH:MM:SS)"] = "BAŞLANGIÇ (SS:DD:SS)",
        ["END (HH:MM:SS)"] = "BİTİŞ (SS:DD:SS)",
        ["PROGRESS"] = "İLERLEME",
        ["The container is the file type. MP4 is the safest general choice. MKV supports many stream types. WebM is intended for browsers. MOV suits Apple workflows. AVI is mainly for older software. MP3, M4A, and WAV create audio-only files."] = "Kapsayıcı dosya türüdür. MP4 en güvenli genel seçimdir. MKV birçok akış türünü destekler. WebM tarayıcılar içindir. MOV Apple iş akışlarına uygundur. AVI daha çok eski yazılımlar içindir. MP3, M4A ve WAV yalnızca ses dosyası oluşturur.",
        ["H.264 plays on almost every device. H.265 creates smaller files but may not play on older devices. VP9 is useful for WebM and browsers. AV1 offers strong compression but is the slowest. Copy keeps the original video without quality loss when the container supports it."] = "H.264 hemen her cihazda oynar. H.265 daha küçük dosyalar oluşturur ancak eski cihazlarda açılmayabilir. VP9 WebM ve tarayıcılar için kullanışlıdır. AV1 güçlü sıkıştırma sunar ancak en yavaşıdır. Kopyala, kapsayıcı desteklediğinde özgün videoyu kalite kaybı olmadan korur.",
        ["CRF targets visual quality, so final size can vary. Fixed Bitrate targets a data rate, making file size more predictable. Use CRF for normal viewing quality and Fixed Bitrate when size or bandwidth matters more."] = "CRF görüntü kalitesini hedefler; bu nedenle son boyut değişebilir. Sabit Bit Hızı bir veri hızını hedefleyerek dosya boyutunu daha öngörülebilir yapar. Normal izleme kalitesi için CRF, boyut veya bant genişliği daha önemliyse Sabit Bit Hızı kullanın.",
        ["In CRF mode, a lower number means higher quality and a larger file; 23 is a common H.264 starting point. In Fixed Bitrate mode, enter kilobits per second: a higher value gives more quality and a larger file."] = "CRF modunda düşük sayı daha yüksek kalite ve daha büyük dosya demektir; 23, H.264 için yaygın bir başlangıçtır. Sabit Bit Hızı modunda saniyedeki kilobit değerini girin: yüksek değer daha fazla kalite ve daha büyük dosya verir.",
        ["Source keeps the original dimensions. A numbered option limits output height while preserving aspect ratio. Lower resolution reduces file size and processing demand. Custom allows an exact width and height."] = "Kaynak özgün boyutları korur. Sayılı seçenekler en-boy oranını koruyarak çıktı yüksekliğini sınırlar. Düşük çözünürlük dosya boyutunu ve işlem yükünü azaltır. Özel, kesin genişlik ve yükseklik girmenizi sağlar.",
        ["Used only when Resolution is Custom. Enter width and height as 1280x720. Even dimensions are the safest choice for common video codecs."] = "Yalnızca Çözünürlük Özel olduğunda kullanılır. Genişlik ve yüksekliği 1280x720 biçiminde girin. Yaygın video kodekleri için çift sayılı boyutlar en güvenli seçimdir.",
        ["Source preserves the original frame rate. 60 is smoother but needs more data. 30 suits most video. 24 gives a cinema-like motion style. Reducing frame rate can reduce file size."] = "Kaynak özgün kare hızını korur. 60 daha akıcıdır ancak daha fazla veri ister. 30 çoğu videoya uygundur. 24 sinema benzeri hareket verir. Kare hızını düşürmek dosya boyutunu azaltabilir.",
        ["Used only when Frame Rate is Custom. Enter the desired frames per second, such as 25 or 29.97. Values above the source frame rate usually add no real motion detail."] = "Yalnızca Kare Hızı Özel olduğunda kullanılır. 25 veya 29.97 gibi istenen saniye başına kare değerini girin. Kaynağın üzerindeki değerler genellikle gerçek hareket ayrıntısı eklemez.",
        ["AAC is broadly compatible with MP4. Opus is efficient for WebM. MP3 suits older players. PCM is uncompressed and large. Copy preserves the original audio without re-encoding when supported. Drop removes audio completely."] = "AAC, MP4 ile geniş uyumludur. Opus, WebM için verimlidir. MP3 eski oynatıcılara uygundur. PCM sıkıştırılmamış ve büyüktür. Kopyala desteklendiğinde özgün sesi yeniden kodlamadan korur. At sesi tamamen kaldırır.",
        ["Audio data rate in kilobits per second. 128 is a compact general setting, 192 provides more detail, and 256 or 320 is useful for music. This value is ignored for Copy, Drop, and uncompressed PCM."] = "Saniyedeki kilobit cinsinden ses veri hızıdır. 128 kompakt genel ayardır, 192 daha fazla ayrıntı sağlar, 256 veya 320 müzik için kullanışlıdır. Kopyala, At ve sıkıştırılmamış PCM seçeneklerinde bu değer kullanılmaz.",
        ["Optional trim start time. Leave empty to begin at the start of the source. Use hours:minutes:seconds, for example 00:01:30."] = "İsteğe bağlı kırpma başlangıcıdır. Kaynağın başından başlamak için boş bırakın. Saat:dakika:saniye biçimini kullanın; örneğin 00:01:30.",
        ["Optional trim end time. Leave empty to continue to the end of the source. The end time must be later than the start time."] = "İsteğe bağlı kırpma bitişidir. Kaynağın sonuna kadar sürdürmek için boş bırakın. Bitiş zamanı başlangıç zamanından sonra olmalıdır.",
        ["ABOUT VIDSHRINK"] = "VIDSHRINK HAKKINDA",
        ["VidShrink is an offline Windows tool for target-size video compression and format conversion. In SHRINK, the target size becomes a total bitrate budget: audio is reserved first, bits per pixel selects CRF or two-pass encoding, resolution steps down when necessary, and oversize output triggers a measured bitrate correction."] = "VidShrink, hedef boyutlu video sıkıştırma ve format dönüştürme için çevrimdışı bir Windows aracıdır. KÜÇÜLT modunda hedef boyut toplam bit hızı bütçesine dönüşür: önce ses payı ayrılır, piksel başına bit değeri CRF veya iki geçişli kodlamayı seçer, gerektiğinde çözünürlük düşürülür ve büyük çıktı ölçülmüş bit hızı düzeltmesini tetikler.",
        ["AUTOMATIC DECISION TABLE"] = "OTOMATİK KARAR TABLOSU",
        [">= 0.10      Keep resolution, quality-first CRF\n0.05-0.10    Keep resolution, two-pass VBR\n0.03-0.05    Halve high frame rates when needed\n< 0.03       Step down the resolution ladder, then two-pass"] = ">= 0.10      Çözünürlüğü koru, kalite öncelikli CRF\n0.05-0.10    Çözünürlüğü koru, iki geçişli VBR\n0.03-0.05    Gerektiğinde yüksek kare hızını yarıya indir\n< 0.03       Çözünürlük basamağını düşür, sonra iki geçiş",
        ["AI MODE"] = "AI MODU",
        ["AI mode only creates a prompt and validates pasted JSON. No AI is embedded, so VidShrink works offline, asks for no API key, and falls back to the complete automatic engine when an answer is malformed or incompatible."] = "AI modu yalnızca istem oluşturur ve yapıştırılan JSON'u doğrular. Gömülü AI olmadığı için VidShrink çevrimdışı çalışır, API anahtarı istemez ve yanıt bozuk ya da uyumsuz olduğunda eksiksiz otomatik motora döner.",
        ["CODECS"] = "KODEKLER",
        ["H.264 offers the broadest compatibility. H.265 compresses more efficiently. VP9 is a strong WebM choice. AV1 maximizes modern compression at higher CPU cost. Stream copy is fastest and lossless when the destination supports the source streams."] = "H.264 en geniş uyumluluğu sunar. H.265 daha verimli sıkıştırır. VP9, WebM için güçlü bir seçimdir. AV1 daha yüksek işlemci maliyetiyle modern sıkıştırmayı en üst düzeye çıkarır. Hedef kaynak akışlarını desteklediğinde akış kopyalama en hızlı ve kayıpsız seçenektir.",
        ["SYSTEM STATUS"] = "SİSTEM DURUMU",
        ["GITHUB / BY TEKNESYUM"] = "GITHUB / TEKNESYUM",
        ["BUY ME A COFFEE"] = "KAHVE ISMARLA",
        ["Idle"] = "Boşta",
        ["FFmpeg: Checking..."] = "FFmpeg: Kontrol Ediliyor..."
    };

    internal static readonly IReadOnlyDictionary<string, string> TurkishToEnglish = EnglishToTurkish.ToDictionary(item => item.Value, item => item.Key);
}
