<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VidShrink.Core\VidShrink.Core.csproj" />
    <ProjectReference Include="..\VidShrink.Ffmpeg\VidShrink.Ffmpeg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\AtkinsonHyperlegibleNext-Regular.ttf" />
    <Resource Include="Fonts\AtkinsonHyperlegibleNext-SemiBold.ttf" />
    <Resource Include="Fonts\AtkinsonHyperlegibleNext-Bold.ttf" />
    <None Include="Fonts\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\VidShrink.png" />
    <Resource Include="Assets\VidShrink.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\VidShrink.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
