<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\VidShrink.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VidShrink.Core\VidShrink.Core.csproj" />
    <ProjectReference Include="..\VidShrink.Ffmpeg\VidShrink.Ffmpeg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\VidShrink.png" />
    <AvaloniaResource Include="Fonts\AtkinsonHyperlegibleNext-Regular.ttf" />
    <AvaloniaResource Include="Fonts\AtkinsonHyperlegibleNext-SemiBold.ttf" />
    <AvaloniaResource Include="Fonts\AtkinsonHyperlegibleNext-Bold.ttf" />
    <None Update="Fonts\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Locales\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Locales\**\*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.20" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
  </ItemGroup>

</Project>
