<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>adcozum</AssemblyName>
    <RootNamespace>adcozum</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\VidShrink.Core\VidShrink.Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\VidShrink.Ffmpeg\VidShrink.Ffmpeg.csproj" />
    <ProjectReference Include="..\..\..\..\tools\VidShrink.Bench\VidShrink.Bench.csproj" />
  </ItemGroup>
</Project>
