<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VidShrink.TepeEgrisi</RootNamespace>
    <AssemblyName>tepe-egrisi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/VidShrink.Core/VidShrink.Core.csproj" />
    <ProjectReference Include="../../src/VidShrink.Ffmpeg/VidShrink.Ffmpeg.csproj" />
  </ItemGroup>

</Project>
